insert into projects (title, category, funding_goal, start_date, end_date) values ('Zaam-Dox', 'Health', 203, '7/3/2019', '11/6/2019');
insert into projects (title, category, funding_goal, start_date, end_date) values ('Vagram', 'Beauty', 530, '7/3/2019', '11/30/2019');
insert into projects (title, category, funding_goal, start_date, end_date) values ('Gembucket', 'Electronics', 446, '7/3/2019', '8/19/2019');
insert into projects (title, category, funding_goal, start_date, end_date) values ('Solarbreeze', 'Shoes', 159, '7/3/2019', '9/26/2019');
insert into projects (title, category, funding_goal, start_date, end_date) values ('Vagram', 'Health', 426, '7/3/2019', '11/20/2019');
insert into projects (title, category, funding_goal, start_date, end_date) values ('Stronghold', 'Grocery', 361, '7/3/2019', '6/8/2020');
insert into projects (title, category, funding_goal, start_date, end_date) values ('Viva', 'Industrial', 576, '7/3/2019', '10/1/2019');
insert into projects (title, category, funding_goal, start_date, end_date) values ('Subin', 'Automotive', 663, '7/3/2019', '1/9/2020');
insert into projects (title, category, funding_goal, start_date, end_date) values ('Keylex', 'Tools', 288, '7/3/2019', '4/27/2020');
insert into projects (title, category, funding_goal, start_date, end_date) values ('Cookley', 'Clothing', 410, '7/3/2019', '11/6/2019');

insert into users (name, age) values ('Aubrey', 45);
insert into users (name, age) values ('Shaughn', 7);
insert into users (name, age) values ('Casi', 95);
insert into users (name, age) values ('Franky', 98);
insert into users (name, age) values ('Edmon', 81);
insert into users (name, age) values ('Walton', 78);
insert into users (name, age) values ('Hailey', 3);
insert into users (name, age) values ('Norean', 41);
insert into users (name, age) values ('Averil', 46);
insert into users (name, age) values ('Angeli', 11);
insert into users (name, age) values ('Janice', 31);
insert into users (name, age) values ('Lem', 54);
insert into users (name, age) values ('Alyson', 13);
insert into users (name, age) values ('Bryanty', 25);
insert into users (name, age) values ('Ode', 96);
insert into users (name, age) values ('Ulysses', 72);
insert into users (name, age) values ('Lizbeth', 89);
insert into users (name, age) values ('Lindi', 85);
insert into users (name, age) values ('Alon', 45);
insert into users (name, age) values ('Ches', 5);


insert into pledges (amount, user_id, project_id) values (36, 13, 3);
insert into pledges (amount, user_id, project_id) values (44, 19, 1);
insert into pledges (amount, user_id, project_id) values (42, 6, 10);
insert into pledges (amount, user_id, project_id) values (14, 2, 9);
insert into pledges (amount, user_id, project_id) values (63, 7, 1);
insert into pledges (amount, user_id, project_id) values (88, 2, 2);
insert into pledges (amount, user_id, project_id) values (45, 9, 6);
insert into pledges (amount, user_id, project_id) values (88, 19, 2);
insert into pledges (amount, user_id, project_id) values (50, 2, 1);
insert into pledges (amount, user_id, project_id) values (15, 4, 10);
insert into pledges (amount, user_id, project_id) values (99, 19, 8);
insert into pledges (amount, user_id, project_id) values (98, 16, 8);
insert into pledges (amount, user_id, project_id) values (13, 13, 6);
insert into pledges (amount, user_id, project_id) values (62, 7, 6);
insert into pledges (amount, user_id, project_id) values (84, 12, 7);
insert into pledges (amount, user_id, project_id) values (78, 11, 5);
insert into pledges (amount, user_id, project_id) values (23, 2, 4);
insert into pledges (amount, user_id, project_id) values (43, 5, 10);
insert into pledges (amount, user_id, project_id) values (65, 2, 10);
insert into pledges (amount, user_id, project_id) values (19, 18, 5);
insert into pledges (amount, user_id, project_id) values (95, 12, 7);
insert into pledges (amount, user_id, project_id) values (15, 8, 9);
insert into pledges (amount, user_id, project_id) values (65, 11, 4);
insert into pledges (amount, user_id, project_id) values (23, 14, 9);
insert into pledges (amount, user_id, project_id) values (84, 18, 9);
insert into pledges (amount, user_id, project_id) values (68, 9, 8);
insert into pledges (amount, user_id, project_id) values (85, 9, 7);
insert into pledges (amount, user_id, project_id) values (84, 18, 9);
insert into pledges (amount, user_id, project_id) values (68, 9, 8);
insert into pledges (amount, user_id, project_id) values (85, 9, 7);